/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { aaveV3AaveReserveOverview } from "../../funcs/aaveV3AaveReserveOverview.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.V1AaveReserveOverviewRequest$inboundSchema,
};

export const tool$aaveV3AaveReserveOverview: ToolDefinition<typeof args> = {
  name: "aave-v3-aave-reserve-overview",
  description: `Reserve Overview

Returns key metrics for Aave Reserves:
- Total Supplied (TVL) in USD
- Total Borrowed in USD
- Utilization Ratio

See below for more info:`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await aaveV3AaveReserveOverview(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
