/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { aaveV3AaveStdRate } from "../../funcs/aaveV3AaveStdRate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.V1AaveStdRateRequest$inboundSchema,
};

export const tool$aaveV3AaveStdRate: ToolDefinition<typeof args> = {
  name: "aave-v3-aave-std-rate",
  description: `Interest Rates: Standard Deviation

Returns the historical standard deviation of lending and borrowing rates for Aave
reserves, illustrating market volatility.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await aaveV3AaveStdRate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
