/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { aaveV3AaveRate } from "../../funcs/aaveV3AaveRate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.V1AaveRateRequest$inboundSchema,
};

export const tool$aaveV3AaveRate: ToolDefinition<typeof args> = {
  name: "aave-v3-aave-rate",
  description: `Interest Rates

Returns the latest APY and APR rates for a specified token on Aave, for both
deposits and loans.

**Annual percentage yield (APY)** is the yearly return/cost after continuous
compounding of the per-second rate stored on-chain. This value is the same value as
seen the on [app.aave.com](
https://app.aave.com/)
but more up-to-date as it is taken directly from the
blockchain every time this endpoint is called.

**Annual percentage rate (APR)** is the yearly simple interest rate (no
compounding).

For APY/APR on loans Aave offers both stable and fixed rates on certain tokens.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await aaveV3AaveRate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
