/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { aaveV3AaveHistoricalTransactions } from "../../funcs/aaveV3AaveHistoricalTransactions.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.V1AaveHistoricalTransactionsRequest$inboundSchema,
};

export const tool$aaveV3AaveHistoricalTransactions: ToolDefinition<
  typeof args
> = {
  name: "aave-v3-aave-historical-transactions",
  description: `Historical Transactions

This endpoint retrieves historical transactions for a user on the AAVE platform.

It returns a list of transactions including deposits, withdrawals, borrows, and
repayments. Each transaction includes details such as the token, amount, timestamp,
and transaction type. This provides a comprehensive view of the user's historical
activity within the AAVE protocol.

⚠️ Data comes from the official Aave subgraph (
https://github.com/aave/protocol-subgraphs)
and thus this particular endpoint may be less reliable than our other endpoints. ⚠️`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await aaveV3AaveHistoricalTransactions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
