/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { erc4626VaultsVaultsVault } from "../../funcs/erc4626VaultsVaultsVault.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.V1VaultsVaultRequest$inboundSchema,
};

export const tool$erc4626VaultsVaultsVault: ToolDefinition<typeof args> = {
  name: "ERC-4626-vaults-vaults-vault",
  description: `Get Vault & User Position

Get Vault data & User Position.

The user position is only included if 'user_address' parameter is included.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await erc4626VaultsVaultsVault(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
