/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { erc4626VaultsVaultsWithdraw } from "../../funcs/erc4626VaultsVaultsWithdraw.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.VaultWithdrawRequest$inboundSchema,
};

export const tool$erc4626VaultsVaultsWithdraw: ToolDefinition<typeof args> = {
  name: "ERC-4626-vaults-vaults-withdraw",
  description: `Withdraw from Vault

Withdraw deposited tokens from a Vault (ERC-4626 Standard).

The passive yield earned on token deposits is represented by the increased value of
the shares received upon depositing tokens. Trade in these shares for the tokens you
deposited plus any accrued yield.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await erc4626VaultsVaultsWithdraw(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
