/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { morphoMorphoMarketPosition } from "../../funcs/morphoMorphoMarketPosition.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.V1MorphoMarketPositionRequest$inboundSchema,
};

export const tool$morphoMorphoMarketPosition: ToolDefinition<typeof args> = {
  name: "morpho-morpho-market-position",
  description: `Check Market Position

Check how many shares you've borrowed and the equivalent token amount of a given
market.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await morphoMorphoMarketPosition(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
