/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { morphoMorphoMarkets } from "../../funcs/morphoMorphoMarkets.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.V1MorphoMarketsRequest$inboundSchema,
};

export const tool$morphoMorphoMarkets: ToolDefinition<typeof args> = {
  name: "morpho-morpho-markets",
  description: `Get Markets

Query a list of markets you can borrow from.

Each market has one unique token that can be borrowed against one unique token that
can be used as collateral.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await morphoMorphoMarkets(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
