/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pendlePendleMarkets } from "../../funcs/pendlePendleMarkets.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.V1PendleMarketsRequest$inboundSchema,
};

export const tool$pendlePendleMarkets: ToolDefinition<typeof args> = {
  name: "pendle-pendle-markets",
  description: `List Market Data

Get a list of active markets.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await pendlePendleMarkets(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
