/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pendlePendleYt } from "../../funcs/pendlePendleYt.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.PendleTradeYtRequest$inboundSchema,
};

export const tool$pendlePendleYt: ToolDefinition<typeof args> = {
  name: "pendle-pendle-yt",
  description: `Trade Yield Token (YT)

Trade Yield Token (YT) for variable yield.

YT is traded with a token of the user's choice.

A sufficient allowance for the Pendle Router on the appropriate token contract must be set
beforehand. For \`action\` set to \`BUY\`, this is the \`token\` contract. For \`action\` set to \`SELL\`, this is the YT contract.
                    <Info>
                    **Required Allowances**

                        In order to make this transaction, token allowances need to be set for the following contracts.

                     - \`PendleRouter\`
                    </Info>
                `,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await pendlePendleYt(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
