/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pendlePendleMarket } from "../../funcs/pendlePendleMarket.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.V1PendleMarketRequest$inboundSchema,
};

export const tool$pendlePendleMarket: ToolDefinition<typeof args> = {
  name: "pendle-pendle-market",
  description: `Get Market & User Position

Get the market's implied APY, maturity date and the associated token data.

The user position is only included if 'user_address' parameter is included.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await pendlePendleMarket(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
