/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pendlePendleRedeemYield } from "../../funcs/pendlePendleRedeemYield.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.PendleRedeemYieldRequest$inboundSchema,
};

export const tool$pendlePendleRedeemYield: ToolDefinition<typeof args> = {
  name: "pendle-pendle-redeem-yield",
  description: `Redeem Claimable Yield

Redeem claimable yield from the market's associated Yield Token (YT).
                    <Info>
                    **Required Allowances**

                        In order to make this transaction, token allowances need to be set for the following contracts.

                     - \`PendleRouter\`
                    </Info>
                `,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await pendlePendleRedeemYield(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
