/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { skySkyPosition } from "../../funcs/skySkyPosition.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.V1SkyPositionRequest$inboundSchema,
};

export const tool$skySkyPosition: ToolDefinition<typeof args> = {
  name: "sky-sky-position",
  description: `Check USDS Position

Check the USDS overall position.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await skySkyPosition(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
