/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { skySkyDeposit } from "../../funcs/skySkyDeposit.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.SkyDepositRequest$inboundSchema,
};

export const tool$skySkyDeposit: ToolDefinition<typeof args> = {
  name: "sky-sky-deposit",
  description: `Deposit USDS

Deposit USDS to earn yield. Deposited USDS is represented as sUSDS.

Allowance must be set on USDS contract for UsdsVault.

There are no fees.
                    <Info>
                    **Required Allowances**

                        In order to make this transaction, token allowances need to be set for the following contracts.

                     - \`SkyUsdsVault\`
                    </Info>
                `,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await skySkyDeposit(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
