/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tokenTokenTransfer } from "../../funcs/tokenTokenTransfer.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.TokenTransferRequest$inboundSchema,
};

export const tool$tokenTokenTransfer: ToolDefinition<typeof args> = {
  name: "token-token-transfer",
  description: `Transfer Tokens

Sends native ETH or ERC20 tokens from the sender's address to another address.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tokenTokenTransfer(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
