/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionBundlerTransactionBundlerExecute } from "../../funcs/transactionBundlerTransactionBundlerExecute.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.MulticallExecuteRequest$inboundSchema,
};

export const tool$transactionBundlerTransactionBundlerExecute: ToolDefinition<
  typeof args
> = {
  name: "transaction-bundler-transaction-bundler-execute",
  description: `Construct Bundled Transaction

Bundle arbitrary transactions together into a single multicall transaction using
EIP-7702.

This endpoint allows bundling multiple contract calls into a single atomic
transaction, reducing gas costs and ensuring all operations succeed or fail
together. The transaction must be authorized using the /authorization endpoint to
prevent replay attacks.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transactionBundlerTransactionBundlerExecute(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
