/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { uniswapV3UniswapLiquidityProvisionInRange } from "../../funcs/uniswapV3UniswapLiquidityProvisionInRange.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.V1UniswapLiquidityProvisionInRangeRequest$inboundSchema,
};

export const tool$uniswapV3UniswapLiquidityProvisionInRange: ToolDefinition<
  typeof args
> = {
  name: "uniswap-v3-uniswap-liquidity-provision-in-range",
  description: `Check if LP is Active.

This endpoint allows users to check whether a specific liquidity provider ()
position is within the active tick range on the uniswap platform.

by providing the token id associated with the position, users can verify if the
position is currently within the tick range where trading occurs. this information
is essential for users to monitor the status of their lp positions and ensure that
they are actively participating in the trading activities within the liquidity pool
and earning trading fees.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await uniswapV3UniswapLiquidityProvisionInRange(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
