/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { uniswapV3UniswapQuoteBuyExactly } from "../../funcs/uniswapV3UniswapQuoteBuyExactly.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.V1UniswapQuoteBuyExactlyRequest$inboundSchema,
};

export const tool$uniswapV3UniswapQuoteBuyExactly: ToolDefinition<typeof args> =
  {
    name: "uniswap-v3-uniswap-quote-buy-exactly",
    description: `Get Quote - to Specified Amount

This endpoint calculates the amount of input tokens required to purchase a
specified amount of output tokens from a Uniswap pool.

It also provides the resulting price after the transaction. The calculation takes
into account the current pool state and the specified fee tier.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await uniswapV3UniswapQuoteBuyExactly(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
