/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { uniswapV3UniswapPoolPrice } from "../../funcs/uniswapV3UniswapPoolPrice.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.V1UniswapPoolPriceRequest$inboundSchema,
};

export const tool$uniswapV3UniswapPoolPrice: ToolDefinition<typeof args> = {
  name: "uniswap-v3-uniswap-pool-price",
  description: `Pool Price

This endpoint calculates the price of a token in a Uniswap pool.

The price is calculated based on the current pool state and the specified fee tier.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await uniswapV3UniswapPoolPrice(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
