/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { swapSwapOdos } from "../funcs/swapSwapOdos.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Swap extends ClientSDK {
  /**
   * Odos Swap
   *
   * @remarks
   * Swap between two tokens using Odos Smart Order Routing.
   *                     <Info>
   *                     **Required Allowances**
   *
   *                         In order to make this transaction, token allowances need to be set for the following contracts.
   *
   *                      - `OdosRouter`
   *                     </Info>
   */
  async swapOdos(
    request: components.OdosSwapRequest,
    options?: RequestOptions,
  ): Promise<components.OdosTransactionResponse> {
    return unwrapAsync(swapSwapOdos(
      this,
      request,
      options,
    ));
  }
}
