/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const V1AaveReserveOverviewChain = {
  Arbitrum: "arbitrum",
  Base: "base",
  Ethereum: "ethereum",
} as const;
export type V1AaveReserveOverviewChain = ClosedEnum<
  typeof V1AaveReserveOverviewChain
>;

export type V1AaveReserveOverviewRequest = {
  chain?: V1AaveReserveOverviewChain | undefined;
  /**
   * Optional block number (defaults to latest).
   */
  block?: number | null | undefined;
  /**
   * The symbol or address of the asset..
   */
  token?: string | undefined;
};

/** @internal */
export const V1AaveReserveOverviewChain$inboundSchema: z.ZodNativeEnum<
  typeof V1AaveReserveOverviewChain
> = z.nativeEnum(V1AaveReserveOverviewChain);

/** @internal */
export const V1AaveReserveOverviewChain$outboundSchema: z.ZodNativeEnum<
  typeof V1AaveReserveOverviewChain
> = V1AaveReserveOverviewChain$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1AaveReserveOverviewChain$ {
  /** @deprecated use `V1AaveReserveOverviewChain$inboundSchema` instead. */
  export const inboundSchema = V1AaveReserveOverviewChain$inboundSchema;
  /** @deprecated use `V1AaveReserveOverviewChain$outboundSchema` instead. */
  export const outboundSchema = V1AaveReserveOverviewChain$outboundSchema;
}

/** @internal */
export const V1AaveReserveOverviewRequest$inboundSchema: z.ZodType<
  V1AaveReserveOverviewRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  chain: V1AaveReserveOverviewChain$inboundSchema.default("arbitrum"),
  block: z.nullable(z.number().int()).optional(),
  token: z.string().default("USDC"),
});

/** @internal */
export type V1AaveReserveOverviewRequest$Outbound = {
  chain: string;
  block?: number | null | undefined;
  token: string;
};

/** @internal */
export const V1AaveReserveOverviewRequest$outboundSchema: z.ZodType<
  V1AaveReserveOverviewRequest$Outbound,
  z.ZodTypeDef,
  V1AaveReserveOverviewRequest
> = z.object({
  chain: V1AaveReserveOverviewChain$outboundSchema.default("arbitrum"),
  block: z.nullable(z.number().int()).optional(),
  token: z.string().default("USDC"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1AaveReserveOverviewRequest$ {
  /** @deprecated use `V1AaveReserveOverviewRequest$inboundSchema` instead. */
  export const inboundSchema = V1AaveReserveOverviewRequest$inboundSchema;
  /** @deprecated use `V1AaveReserveOverviewRequest$outboundSchema` instead. */
  export const outboundSchema = V1AaveReserveOverviewRequest$outboundSchema;
  /** @deprecated use `V1AaveReserveOverviewRequest$Outbound` instead. */
  export type Outbound = V1AaveReserveOverviewRequest$Outbound;
}

export function v1AaveReserveOverviewRequestToJSON(
  v1AaveReserveOverviewRequest: V1AaveReserveOverviewRequest,
): string {
  return JSON.stringify(
    V1AaveReserveOverviewRequest$outboundSchema.parse(
      v1AaveReserveOverviewRequest,
    ),
  );
}

export function v1AaveReserveOverviewRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1AaveReserveOverviewRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AaveReserveOverviewRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AaveReserveOverviewRequest' from JSON`,
  );
}
