/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const V1AaveAvgRateChain = {
  Arbitrum: "arbitrum",
  Base: "base",
  Ethereum: "ethereum",
} as const;
export type V1AaveAvgRateChain = ClosedEnum<typeof V1AaveAvgRateChain>;

export type V1AaveAvgRateRequest = {
  chain?: V1AaveAvgRateChain | undefined;
  /**
   * Optional block number (defaults to latest).
   */
  block?: number | null | undefined;
  /**
   * The symbol or address of the token..
   */
  token?: string | undefined;
  /**
   * The number of days for which the average shall be calculated.
   */
  days?: number | undefined;
};

/** @internal */
export const V1AaveAvgRateChain$inboundSchema: z.ZodNativeEnum<
  typeof V1AaveAvgRateChain
> = z.nativeEnum(V1AaveAvgRateChain);

/** @internal */
export const V1AaveAvgRateChain$outboundSchema: z.ZodNativeEnum<
  typeof V1AaveAvgRateChain
> = V1AaveAvgRateChain$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1AaveAvgRateChain$ {
  /** @deprecated use `V1AaveAvgRateChain$inboundSchema` instead. */
  export const inboundSchema = V1AaveAvgRateChain$inboundSchema;
  /** @deprecated use `V1AaveAvgRateChain$outboundSchema` instead. */
  export const outboundSchema = V1AaveAvgRateChain$outboundSchema;
}

/** @internal */
export const V1AaveAvgRateRequest$inboundSchema: z.ZodType<
  V1AaveAvgRateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  chain: V1AaveAvgRateChain$inboundSchema.default("ethereum"),
  block: z.nullable(z.number().int()).optional(),
  token: z.string().default("USDC"),
  days: z.number().int().default(2),
});

/** @internal */
export type V1AaveAvgRateRequest$Outbound = {
  chain: string;
  block?: number | null | undefined;
  token: string;
  days: number;
};

/** @internal */
export const V1AaveAvgRateRequest$outboundSchema: z.ZodType<
  V1AaveAvgRateRequest$Outbound,
  z.ZodTypeDef,
  V1AaveAvgRateRequest
> = z.object({
  chain: V1AaveAvgRateChain$outboundSchema.default("ethereum"),
  block: z.nullable(z.number().int()).optional(),
  token: z.string().default("USDC"),
  days: z.number().int().default(2),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1AaveAvgRateRequest$ {
  /** @deprecated use `V1AaveAvgRateRequest$inboundSchema` instead. */
  export const inboundSchema = V1AaveAvgRateRequest$inboundSchema;
  /** @deprecated use `V1AaveAvgRateRequest$outboundSchema` instead. */
  export const outboundSchema = V1AaveAvgRateRequest$outboundSchema;
  /** @deprecated use `V1AaveAvgRateRequest$Outbound` instead. */
  export type Outbound = V1AaveAvgRateRequest$Outbound;
}

export function v1AaveAvgRateRequestToJSON(
  v1AaveAvgRateRequest: V1AaveAvgRateRequest,
): string {
  return JSON.stringify(
    V1AaveAvgRateRequest$outboundSchema.parse(v1AaveAvgRateRequest),
  );
}

export function v1AaveAvgRateRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1AaveAvgRateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AaveAvgRateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AaveAvgRateRequest' from JSON`,
  );
}
