/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AaveRateResponse = {
  /**
   * Variable rate APY for deposits.
   */
  supplyApyVariableRate: string;
  /**
   * Variable rate APR for deposits.
   */
  supplyAprVariableRate: string;
  /**
   * Variable rate APY for loans.
   */
  borrowApyVariableRate: string;
  /**
   * Variable rate APR for loans.
   */
  borrowAprVariableRate: string;
  /**
   * Fixed rate APY for loans.
   */
  borrowApyFixedRate: string;
  /**
   * Fixed rate APR for loans.
   */
  borrowAprFixedRate: string;
};

/** @internal */
export const AaveRateResponse$inboundSchema: z.ZodType<
  AaveRateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  supply_apy_variable_rate: z.string(),
  supply_apr_variable_rate: z.string(),
  borrow_apy_variable_rate: z.string(),
  borrow_apr_variable_rate: z.string(),
  borrow_apy_fixed_rate: z.string(),
  borrow_apr_fixed_rate: z.string(),
}).transform((v) => {
  return remap$(v, {
    "supply_apy_variable_rate": "supplyApyVariableRate",
    "supply_apr_variable_rate": "supplyAprVariableRate",
    "borrow_apy_variable_rate": "borrowApyVariableRate",
    "borrow_apr_variable_rate": "borrowAprVariableRate",
    "borrow_apy_fixed_rate": "borrowApyFixedRate",
    "borrow_apr_fixed_rate": "borrowAprFixedRate",
  });
});

/** @internal */
export type AaveRateResponse$Outbound = {
  supply_apy_variable_rate: string;
  supply_apr_variable_rate: string;
  borrow_apy_variable_rate: string;
  borrow_apr_variable_rate: string;
  borrow_apy_fixed_rate: string;
  borrow_apr_fixed_rate: string;
};

/** @internal */
export const AaveRateResponse$outboundSchema: z.ZodType<
  AaveRateResponse$Outbound,
  z.ZodTypeDef,
  AaveRateResponse
> = z.object({
  supplyApyVariableRate: z.string(),
  supplyAprVariableRate: z.string(),
  borrowApyVariableRate: z.string(),
  borrowAprVariableRate: z.string(),
  borrowApyFixedRate: z.string(),
  borrowAprFixedRate: z.string(),
}).transform((v) => {
  return remap$(v, {
    supplyApyVariableRate: "supply_apy_variable_rate",
    supplyAprVariableRate: "supply_apr_variable_rate",
    borrowApyVariableRate: "borrow_apy_variable_rate",
    borrowAprVariableRate: "borrow_apr_variable_rate",
    borrowApyFixedRate: "borrow_apy_fixed_rate",
    borrowAprFixedRate: "borrow_apr_fixed_rate",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AaveRateResponse$ {
  /** @deprecated use `AaveRateResponse$inboundSchema` instead. */
  export const inboundSchema = AaveRateResponse$inboundSchema;
  /** @deprecated use `AaveRateResponse$outboundSchema` instead. */
  export const outboundSchema = AaveRateResponse$outboundSchema;
  /** @deprecated use `AaveRateResponse$Outbound` instead. */
  export type Outbound = AaveRateResponse$Outbound;
}

export function aaveRateResponseToJSON(
  aaveRateResponse: AaveRateResponse,
): string {
  return JSON.stringify(
    AaveRateResponse$outboundSchema.parse(aaveRateResponse),
  );
}

export function aaveRateResponseFromJSON(
  jsonString: string,
): SafeParseResult<AaveRateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AaveRateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AaveRateResponse' from JSON`,
  );
}
