/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AerodromeSlipstreamPoolPriceResponse = {
  /**
   * The first token in the pool.
   */
  tokenIn: string;
  /**
   * The second token in the pool.
   */
  tokenOut: string;
  /**
   * The price of the pool. This is expressed as an instantaneous amount of how
   *
   * @remarks
   * many token0 you need to buy 1 token1. In any swap this will not change during the trade; use
   * the quote endpoint to get a better idea of how much you will pay!
   */
  price: string;
  /**
   * The current tick in the pool. This is a number that represents the price of
   *
   * @remarks
   * the pool according to the aerodrome_slipstream v3 concentrated liquidity concept.
   */
  tick: number;
};

/** @internal */
export const AerodromeSlipstreamPoolPriceResponse$inboundSchema: z.ZodType<
  AerodromeSlipstreamPoolPriceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  token_in: z.string(),
  token_out: z.string(),
  price: z.string(),
  tick: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "token_in": "tokenIn",
    "token_out": "tokenOut",
  });
});

/** @internal */
export type AerodromeSlipstreamPoolPriceResponse$Outbound = {
  token_in: string;
  token_out: string;
  price: string;
  tick: number;
};

/** @internal */
export const AerodromeSlipstreamPoolPriceResponse$outboundSchema: z.ZodType<
  AerodromeSlipstreamPoolPriceResponse$Outbound,
  z.ZodTypeDef,
  AerodromeSlipstreamPoolPriceResponse
> = z.object({
  tokenIn: z.string(),
  tokenOut: z.string(),
  price: z.string(),
  tick: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    tokenIn: "token_in",
    tokenOut: "token_out",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AerodromeSlipstreamPoolPriceResponse$ {
  /** @deprecated use `AerodromeSlipstreamPoolPriceResponse$inboundSchema` instead. */
  export const inboundSchema =
    AerodromeSlipstreamPoolPriceResponse$inboundSchema;
  /** @deprecated use `AerodromeSlipstreamPoolPriceResponse$outboundSchema` instead. */
  export const outboundSchema =
    AerodromeSlipstreamPoolPriceResponse$outboundSchema;
  /** @deprecated use `AerodromeSlipstreamPoolPriceResponse$Outbound` instead. */
  export type Outbound = AerodromeSlipstreamPoolPriceResponse$Outbound;
}

export function aerodromeSlipstreamPoolPriceResponseToJSON(
  aerodromeSlipstreamPoolPriceResponse: AerodromeSlipstreamPoolPriceResponse,
): string {
  return JSON.stringify(
    AerodromeSlipstreamPoolPriceResponse$outboundSchema.parse(
      aerodromeSlipstreamPoolPriceResponse,
    ),
  );
}

export function aerodromeSlipstreamPoolPriceResponseFromJSON(
  jsonString: string,
): SafeParseResult<AerodromeSlipstreamPoolPriceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AerodromeSlipstreamPoolPriceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AerodromeSlipstreamPoolPriceResponse' from JSON`,
  );
}
