/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The desired amount of the first token to deposit
 */
export type AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired =
  | number
  | string;

/**
 * The desired amount of the second token to deposit
 */
export type AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired =
  | number
  | string;

/**
 * The minimum amount of the first token to deposit
 */
export type AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min =
  | number
  | string;

/**
 * The minimum amount of the second token to deposit
 */
export type AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min =
  | number
  | string;

/**
 * Parameters model for minting a new liquidity position.
 */
export type AerodromeSlipstreamMintLiquidityProvisionParams = {
  actionType?: "AERODROME_SLIPSTREAM_MINT_LIQUIDITY_PROVISION" | undefined;
  /**
   * The symbol or address of the first token in the pair.
   */
  token0: string;
  /**
   * The symbol or address of the second token in the pair.
   */
  token1: string;
  /**
   * The tick spacing of the pool
   */
  tickSpacing: number;
  /**
   * The lower tick of the range to mint the position in
   */
  tickLower: number;
  /**
   * The upper tick of the range to mint the position in
   */
  tickUpper: number;
  /**
   * The desired amount of the first token to deposit
   */
  amount0Desired: number | string;
  /**
   * The desired amount of the second token to deposit
   */
  amount1Desired: number | string;
  /**
   * The minimum amount of the first token to deposit
   */
  amount0Min: number | string;
  /**
   * The minimum amount of the second token to deposit
   */
  amount1Min: number | string;
  /**
   * The address that will receive the LP tokens
   */
  recipient?: string | null | undefined;
};

/** @internal */
export const AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired$inboundSchema:
  z.ZodType<
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired,
    z.ZodTypeDef,
    unknown
  > = z.union([z.number(), z.string()]);

/** @internal */
export type AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired$Outbound =
  | number
  | string;

/** @internal */
export const AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired$outboundSchema:
  z.ZodType<
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired$Outbound,
    z.ZodTypeDef,
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired
  > = z.union([z.number(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired$ {
  /** @deprecated use `AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired$inboundSchema` instead. */
  export const inboundSchema =
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired$inboundSchema;
  /** @deprecated use `AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired$outboundSchema` instead. */
  export const outboundSchema =
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired$outboundSchema;
  /** @deprecated use `AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired$Outbound` instead. */
  export type Outbound =
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired$Outbound;
}

export function aerodromeSlipstreamMintLiquidityProvisionParamsAmount0DesiredToJSON(
  aerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired:
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired,
): string {
  return JSON.stringify(
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired$outboundSchema
      .parse(aerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired),
  );
}

export function aerodromeSlipstreamMintLiquidityProvisionParamsAmount0DesiredFromJSON(
  jsonString: string,
): SafeParseResult<
  AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Desired' from JSON`,
  );
}

/** @internal */
export const AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired$inboundSchema:
  z.ZodType<
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired,
    z.ZodTypeDef,
    unknown
  > = z.union([z.number(), z.string()]);

/** @internal */
export type AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired$Outbound =
  | number
  | string;

/** @internal */
export const AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired$outboundSchema:
  z.ZodType<
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired$Outbound,
    z.ZodTypeDef,
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired
  > = z.union([z.number(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired$ {
  /** @deprecated use `AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired$inboundSchema` instead. */
  export const inboundSchema =
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired$inboundSchema;
  /** @deprecated use `AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired$outboundSchema` instead. */
  export const outboundSchema =
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired$outboundSchema;
  /** @deprecated use `AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired$Outbound` instead. */
  export type Outbound =
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired$Outbound;
}

export function aerodromeSlipstreamMintLiquidityProvisionParamsAmount1DesiredToJSON(
  aerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired:
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired,
): string {
  return JSON.stringify(
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired$outboundSchema
      .parse(aerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired),
  );
}

export function aerodromeSlipstreamMintLiquidityProvisionParamsAmount1DesiredFromJSON(
  jsonString: string,
): SafeParseResult<
  AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Desired' from JSON`,
  );
}

/** @internal */
export const AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min$inboundSchema:
  z.ZodType<
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min,
    z.ZodTypeDef,
    unknown
  > = z.union([z.number(), z.string()]);

/** @internal */
export type AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min$Outbound =
  | number
  | string;

/** @internal */
export const AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min$outboundSchema:
  z.ZodType<
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min$Outbound,
    z.ZodTypeDef,
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min
  > = z.union([z.number(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min$ {
  /** @deprecated use `AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min$inboundSchema` instead. */
  export const inboundSchema =
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min$inboundSchema;
  /** @deprecated use `AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min$outboundSchema` instead. */
  export const outboundSchema =
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min$outboundSchema;
  /** @deprecated use `AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min$Outbound` instead. */
  export type Outbound =
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min$Outbound;
}

export function aerodromeSlipstreamMintLiquidityProvisionParamsAmount0MinToJSON(
  aerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min:
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min,
): string {
  return JSON.stringify(
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min$outboundSchema
      .parse(aerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min),
  );
}

export function aerodromeSlipstreamMintLiquidityProvisionParamsAmount0MinFromJSON(
  jsonString: string,
): SafeParseResult<
  AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'AerodromeSlipstreamMintLiquidityProvisionParamsAmount0Min' from JSON`,
  );
}

/** @internal */
export const AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min$inboundSchema:
  z.ZodType<
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min,
    z.ZodTypeDef,
    unknown
  > = z.union([z.number(), z.string()]);

/** @internal */
export type AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min$Outbound =
  | number
  | string;

/** @internal */
export const AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min$outboundSchema:
  z.ZodType<
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min$Outbound,
    z.ZodTypeDef,
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min
  > = z.union([z.number(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min$ {
  /** @deprecated use `AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min$inboundSchema` instead. */
  export const inboundSchema =
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min$inboundSchema;
  /** @deprecated use `AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min$outboundSchema` instead. */
  export const outboundSchema =
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min$outboundSchema;
  /** @deprecated use `AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min$Outbound` instead. */
  export type Outbound =
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min$Outbound;
}

export function aerodromeSlipstreamMintLiquidityProvisionParamsAmount1MinToJSON(
  aerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min:
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min,
): string {
  return JSON.stringify(
    AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min$outboundSchema
      .parse(aerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min),
  );
}

export function aerodromeSlipstreamMintLiquidityProvisionParamsAmount1MinFromJSON(
  jsonString: string,
): SafeParseResult<
  AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'AerodromeSlipstreamMintLiquidityProvisionParamsAmount1Min' from JSON`,
  );
}

/** @internal */
export const AerodromeSlipstreamMintLiquidityProvisionParams$inboundSchema:
  z.ZodType<
    AerodromeSlipstreamMintLiquidityProvisionParams,
    z.ZodTypeDef,
    unknown
  > = z.object({
    action_type: z.literal("AERODROME_SLIPSTREAM_MINT_LIQUIDITY_PROVISION")
      .default("AERODROME_SLIPSTREAM_MINT_LIQUIDITY_PROVISION"),
    token0: z.string(),
    token1: z.string(),
    tick_spacing: z.number().int(),
    tick_lower: z.number().int(),
    tick_upper: z.number().int(),
    amount0_desired: z.union([z.number(), z.string()]),
    amount1_desired: z.union([z.number(), z.string()]),
    amount0_min: z.union([z.number(), z.string()]),
    amount1_min: z.union([z.number(), z.string()]),
    recipient: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "action_type": "actionType",
      "tick_spacing": "tickSpacing",
      "tick_lower": "tickLower",
      "tick_upper": "tickUpper",
      "amount0_desired": "amount0Desired",
      "amount1_desired": "amount1Desired",
      "amount0_min": "amount0Min",
      "amount1_min": "amount1Min",
    });
  });

/** @internal */
export type AerodromeSlipstreamMintLiquidityProvisionParams$Outbound = {
  action_type: "AERODROME_SLIPSTREAM_MINT_LIQUIDITY_PROVISION";
  token0: string;
  token1: string;
  tick_spacing: number;
  tick_lower: number;
  tick_upper: number;
  amount0_desired: number | string;
  amount1_desired: number | string;
  amount0_min: number | string;
  amount1_min: number | string;
  recipient?: string | null | undefined;
};

/** @internal */
export const AerodromeSlipstreamMintLiquidityProvisionParams$outboundSchema:
  z.ZodType<
    AerodromeSlipstreamMintLiquidityProvisionParams$Outbound,
    z.ZodTypeDef,
    AerodromeSlipstreamMintLiquidityProvisionParams
  > = z.object({
    actionType: z.literal("AERODROME_SLIPSTREAM_MINT_LIQUIDITY_PROVISION")
      .default("AERODROME_SLIPSTREAM_MINT_LIQUIDITY_PROVISION" as const),
    token0: z.string(),
    token1: z.string(),
    tickSpacing: z.number().int(),
    tickLower: z.number().int(),
    tickUpper: z.number().int(),
    amount0Desired: z.union([z.number(), z.string()]),
    amount1Desired: z.union([z.number(), z.string()]),
    amount0Min: z.union([z.number(), z.string()]),
    amount1Min: z.union([z.number(), z.string()]),
    recipient: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      actionType: "action_type",
      tickSpacing: "tick_spacing",
      tickLower: "tick_lower",
      tickUpper: "tick_upper",
      amount0Desired: "amount0_desired",
      amount1Desired: "amount1_desired",
      amount0Min: "amount0_min",
      amount1Min: "amount1_min",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AerodromeSlipstreamMintLiquidityProvisionParams$ {
  /** @deprecated use `AerodromeSlipstreamMintLiquidityProvisionParams$inboundSchema` instead. */
  export const inboundSchema =
    AerodromeSlipstreamMintLiquidityProvisionParams$inboundSchema;
  /** @deprecated use `AerodromeSlipstreamMintLiquidityProvisionParams$outboundSchema` instead. */
  export const outboundSchema =
    AerodromeSlipstreamMintLiquidityProvisionParams$outboundSchema;
  /** @deprecated use `AerodromeSlipstreamMintLiquidityProvisionParams$Outbound` instead. */
  export type Outbound =
    AerodromeSlipstreamMintLiquidityProvisionParams$Outbound;
}

export function aerodromeSlipstreamMintLiquidityProvisionParamsToJSON(
  aerodromeSlipstreamMintLiquidityProvisionParams:
    AerodromeSlipstreamMintLiquidityProvisionParams,
): string {
  return JSON.stringify(
    AerodromeSlipstreamMintLiquidityProvisionParams$outboundSchema.parse(
      aerodromeSlipstreamMintLiquidityProvisionParams,
    ),
  );
}

export function aerodromeSlipstreamMintLiquidityProvisionParamsFromJSON(
  jsonString: string,
): SafeParseResult<
  AerodromeSlipstreamMintLiquidityProvisionParams,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AerodromeSlipstreamMintLiquidityProvisionParams$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AerodromeSlipstreamMintLiquidityProvisionParams' from JSON`,
  );
}
