/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState =
  {
    pnlUsd: string;
    borrowAssets: string;
    borrowShares: string;
    borrowAssetsUsd: string;
    collateral: string;
    collateralUsd: string;
    supplyAssets: string;
    supplyShares: string;
    supplyAssetsUsd: string;
  };

/** @internal */
export const CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState$inboundSchema:
  z.ZodType<
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState,
    z.ZodTypeDef,
    unknown
  > = z.object({
    pnlUsd: z.string(),
    borrowAssets: z.string(),
    borrowShares: z.string(),
    borrowAssetsUsd: z.string(),
    collateral: z.string(),
    collateralUsd: z.string(),
    supplyAssets: z.string(),
    supplyShares: z.string(),
    supplyAssetsUsd: z.string(),
  });

/** @internal */
export type CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState$Outbound =
  {
    pnlUsd: string;
    borrowAssets: string;
    borrowShares: string;
    borrowAssetsUsd: string;
    collateral: string;
    collateralUsd: string;
    supplyAssets: string;
    supplyShares: string;
    supplyAssetsUsd: string;
  };

/** @internal */
export const CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState$outboundSchema:
  z.ZodType<
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState$Outbound,
    z.ZodTypeDef,
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState
  > = z.object({
    pnlUsd: z.string(),
    borrowAssets: z.string(),
    borrowShares: z.string(),
    borrowAssetsUsd: z.string(),
    collateral: z.string(),
    collateralUsd: z.string(),
    supplyAssets: z.string(),
    supplyShares: z.string(),
    supplyAssetsUsd: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState$ {
  /** @deprecated use `CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState$inboundSchema` instead. */
  export const inboundSchema =
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState$inboundSchema;
  /** @deprecated use `CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState$outboundSchema` instead. */
  export const outboundSchema =
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState$outboundSchema;
  /** @deprecated use `CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState$Outbound` instead. */
  export type Outbound =
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState$Outbound;
}

export function compassApiBackendModelsMorphoReadResponseCheckUserPositionMarketStateToJSON(
  compassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState:
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState,
): string {
  return JSON.stringify(
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState$outboundSchema
      .parse(
        compassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState,
      ),
  );
}

export function compassApiBackendModelsMorphoReadResponseCheckUserPositionMarketStateFromJSON(
  jsonString: string,
): SafeParseResult<
  CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CompassApiBackendModelsMorphoReadResponseCheckUserPositionMarketState' from JSON`,
  );
}
