/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CompassApiBackendModelsMorphoReadResponseGetMarketApyData = {
  borrowApy: string;
  netBorrowApy: string;
  netSupplyApy: string;
  supplyApy: string;
};

/** @internal */
export const CompassApiBackendModelsMorphoReadResponseGetMarketApyData$inboundSchema:
  z.ZodType<
    CompassApiBackendModelsMorphoReadResponseGetMarketApyData,
    z.ZodTypeDef,
    unknown
  > = z.object({
    borrowApy: z.string(),
    netBorrowApy: z.string(),
    netSupplyApy: z.string(),
    supplyApy: z.string(),
  });

/** @internal */
export type CompassApiBackendModelsMorphoReadResponseGetMarketApyData$Outbound =
  {
    borrowApy: string;
    netBorrowApy: string;
    netSupplyApy: string;
    supplyApy: string;
  };

/** @internal */
export const CompassApiBackendModelsMorphoReadResponseGetMarketApyData$outboundSchema:
  z.ZodType<
    CompassApiBackendModelsMorphoReadResponseGetMarketApyData$Outbound,
    z.ZodTypeDef,
    CompassApiBackendModelsMorphoReadResponseGetMarketApyData
  > = z.object({
    borrowApy: z.string(),
    netBorrowApy: z.string(),
    netSupplyApy: z.string(),
    supplyApy: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CompassApiBackendModelsMorphoReadResponseGetMarketApyData$ {
  /** @deprecated use `CompassApiBackendModelsMorphoReadResponseGetMarketApyData$inboundSchema` instead. */
  export const inboundSchema =
    CompassApiBackendModelsMorphoReadResponseGetMarketApyData$inboundSchema;
  /** @deprecated use `CompassApiBackendModelsMorphoReadResponseGetMarketApyData$outboundSchema` instead. */
  export const outboundSchema =
    CompassApiBackendModelsMorphoReadResponseGetMarketApyData$outboundSchema;
  /** @deprecated use `CompassApiBackendModelsMorphoReadResponseGetMarketApyData$Outbound` instead. */
  export type Outbound =
    CompassApiBackendModelsMorphoReadResponseGetMarketApyData$Outbound;
}

export function compassApiBackendModelsMorphoReadResponseGetMarketApyDataToJSON(
  compassApiBackendModelsMorphoReadResponseGetMarketApyData:
    CompassApiBackendModelsMorphoReadResponseGetMarketApyData,
): string {
  return JSON.stringify(
    CompassApiBackendModelsMorphoReadResponseGetMarketApyData$outboundSchema
      .parse(compassApiBackendModelsMorphoReadResponseGetMarketApyData),
  );
}

export function compassApiBackendModelsMorphoReadResponseGetMarketApyDataFromJSON(
  jsonString: string,
): SafeParseResult<
  CompassApiBackendModelsMorphoReadResponseGetMarketApyData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CompassApiBackendModelsMorphoReadResponseGetMarketApyData$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CompassApiBackendModelsMorphoReadResponseGetMarketApyData' from JSON`,
  );
}
