/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset = {
  name: string;
  symbol: string;
  address: string;
  decimals: number;
  priceUsd: string;
  logoURI: string | null;
};

/** @internal */
export const CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset$inboundSchema:
  z.ZodType<
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset,
    z.ZodTypeDef,
    unknown
  > = z.object({
    name: z.string(),
    symbol: z.string(),
    address: z.string(),
    decimals: z.number().int(),
    priceUsd: z.string(),
    logoURI: z.nullable(z.string()),
  });

/** @internal */
export type CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset$Outbound =
  {
    name: string;
    symbol: string;
    address: string;
    decimals: number;
    priceUsd: string;
    logoURI: string | null;
  };

/** @internal */
export const CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset$outboundSchema:
  z.ZodType<
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset$Outbound,
    z.ZodTypeDef,
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset
  > = z.object({
    name: z.string(),
    symbol: z.string(),
    address: z.string(),
    decimals: z.number().int(),
    priceUsd: z.string(),
    logoURI: z.nullable(z.string()),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset$ {
  /** @deprecated use `CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset$inboundSchema` instead. */
  export const inboundSchema =
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset$inboundSchema;
  /** @deprecated use `CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset$outboundSchema` instead. */
  export const outboundSchema =
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset$outboundSchema;
  /** @deprecated use `CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset$Outbound` instead. */
  export type Outbound =
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset$Outbound;
}

export function compassApiBackendModelsMorphoReadResponseCheckUserPositionAssetToJSON(
  compassApiBackendModelsMorphoReadResponseCheckUserPositionAsset:
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset,
): string {
  return JSON.stringify(
    CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset$outboundSchema
      .parse(compassApiBackendModelsMorphoReadResponseCheckUserPositionAsset),
  );
}

export function compassApiBackendModelsMorphoReadResponseCheckUserPositionAssetFromJSON(
  jsonString: string,
): SafeParseResult<
  CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CompassApiBackendModelsMorphoReadResponseCheckUserPositionAsset' from JSON`,
  );
}
