/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Reserve,
  Reserve$inboundSchema,
  Reserve$Outbound,
  Reserve$outboundSchema,
} from "./reserve.js";

export type RedeemUnderlying = {
  /**
   * The id of a historical transaction on aave
   */
  id: string;
  /**
   * Timestamp in unix time
   */
  timestamp: number;
  /**
   * Transaction hash. You can paste these into the search bar on etherscan
   */
  txHash: string;
  /**
   * Quantity of token
   */
  amount: number;
  reserve: Reserve;
  /**
   * Price of token in USD
   */
  assetPriceUSD: number;
  /**
   * The type of transaction
   */
  action: string;
  block: number;
};

/** @internal */
export const RedeemUnderlying$inboundSchema: z.ZodType<
  RedeemUnderlying,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  timestamp: z.number().int(),
  txHash: z.string(),
  amount: z.number(),
  reserve: Reserve$inboundSchema,
  assetPriceUSD: z.number(),
  action: z.string(),
  block: z.number().int(),
});

/** @internal */
export type RedeemUnderlying$Outbound = {
  id: string;
  timestamp: number;
  txHash: string;
  amount: number;
  reserve: Reserve$Outbound;
  assetPriceUSD: number;
  action: string;
  block: number;
};

/** @internal */
export const RedeemUnderlying$outboundSchema: z.ZodType<
  RedeemUnderlying$Outbound,
  z.ZodTypeDef,
  RedeemUnderlying
> = z.object({
  id: z.string(),
  timestamp: z.number().int(),
  txHash: z.string(),
  amount: z.number(),
  reserve: Reserve$outboundSchema,
  assetPriceUSD: z.number(),
  action: z.string(),
  block: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RedeemUnderlying$ {
  /** @deprecated use `RedeemUnderlying$inboundSchema` instead. */
  export const inboundSchema = RedeemUnderlying$inboundSchema;
  /** @deprecated use `RedeemUnderlying$outboundSchema` instead. */
  export const outboundSchema = RedeemUnderlying$outboundSchema;
  /** @deprecated use `RedeemUnderlying$Outbound` instead. */
  export type Outbound = RedeemUnderlying$Outbound;
}

export function redeemUnderlyingToJSON(
  redeemUnderlying: RedeemUnderlying,
): string {
  return JSON.stringify(
    RedeemUnderlying$outboundSchema.parse(redeemUnderlying),
  );
}

export function redeemUnderlyingFromJSON(
  jsonString: string,
): SafeParseResult<RedeemUnderlying, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedeemUnderlying$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedeemUnderlying' from JSON`,
  );
}
