/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Reserve,
  Reserve$inboundSchema,
  Reserve$Outbound,
  Reserve$outboundSchema,
} from "./reserve.js";

export type Supply = {
  /**
   * The id of a historical transaction on aave
   */
  id: string;
  /**
   * Timestamp in unix time
   */
  timestamp: number;
  /**
   * Transaction hash. You can paste these into the search bar on etherscan
   */
  txHash: string;
  /**
   * Quantity of token
   */
  amount: number;
  reserve: Reserve;
  /**
   * Price of token in USD
   */
  assetPriceUSD: number;
  /**
   * The type of transaction
   */
  action?: "Supply" | undefined;
  block: number;
};

/** @internal */
export const Supply$inboundSchema: z.ZodType<Supply, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    timestamp: z.number().int(),
    txHash: z.string(),
    amount: z.number(),
    reserve: Reserve$inboundSchema,
    assetPriceUSD: z.number(),
    action: z.literal("Supply").default("Supply").optional(),
    block: z.number().int(),
  });

/** @internal */
export type Supply$Outbound = {
  id: string;
  timestamp: number;
  txHash: string;
  amount: number;
  reserve: Reserve$Outbound;
  assetPriceUSD: number;
  action: "Supply";
  block: number;
};

/** @internal */
export const Supply$outboundSchema: z.ZodType<
  Supply$Outbound,
  z.ZodTypeDef,
  Supply
> = z.object({
  id: z.string(),
  timestamp: z.number().int(),
  txHash: z.string(),
  amount: z.number(),
  reserve: Reserve$outboundSchema,
  assetPriceUSD: z.number(),
  action: z.literal("Supply").default("Supply" as const),
  block: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Supply$ {
  /** @deprecated use `Supply$inboundSchema` instead. */
  export const inboundSchema = Supply$inboundSchema;
  /** @deprecated use `Supply$outboundSchema` instead. */
  export const outboundSchema = Supply$outboundSchema;
  /** @deprecated use `Supply$Outbound` instead. */
  export type Outbound = Supply$Outbound;
}

export function supplyToJSON(supply: Supply): string {
  return JSON.stringify(Supply$outboundSchema.parse(supply));
}

export function supplyFromJSON(
  jsonString: string,
): SafeParseResult<Supply, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Supply$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Supply' from JSON`,
  );
}
