/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UniswapPositionsSolidityResponse = {
  nonce: number;
  operator: string;
  token0: string;
  token1: string;
  fee: number;
  tickLower: number;
  tickUpper: number;
  liquidity: number;
  feeGrowthInside0LastX128: number;
  feeGrowthInside1LastX128: number;
  tokensOwed0: number;
  tokensOwed1: number;
  lpTokenAddress?: string | null | undefined;
};

/** @internal */
export const UniswapPositionsSolidityResponse$inboundSchema: z.ZodType<
  UniswapPositionsSolidityResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  nonce: z.number().int(),
  operator: z.string(),
  token0: z.string(),
  token1: z.string(),
  fee: z.number().int(),
  tick_lower: z.number().int(),
  tick_upper: z.number().int(),
  liquidity: z.number().int(),
  fee_growth_inside0_last_x128: z.number().int(),
  fee_growth_inside1_last_x128: z.number().int(),
  tokens_owed0: z.number().int(),
  tokens_owed1: z.number().int(),
  lp_token_address: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "tick_lower": "tickLower",
    "tick_upper": "tickUpper",
    "fee_growth_inside0_last_x128": "feeGrowthInside0LastX128",
    "fee_growth_inside1_last_x128": "feeGrowthInside1LastX128",
    "tokens_owed0": "tokensOwed0",
    "tokens_owed1": "tokensOwed1",
    "lp_token_address": "lpTokenAddress",
  });
});

/** @internal */
export type UniswapPositionsSolidityResponse$Outbound = {
  nonce: number;
  operator: string;
  token0: string;
  token1: string;
  fee: number;
  tick_lower: number;
  tick_upper: number;
  liquidity: number;
  fee_growth_inside0_last_x128: number;
  fee_growth_inside1_last_x128: number;
  tokens_owed0: number;
  tokens_owed1: number;
  lp_token_address?: string | null | undefined;
};

/** @internal */
export const UniswapPositionsSolidityResponse$outboundSchema: z.ZodType<
  UniswapPositionsSolidityResponse$Outbound,
  z.ZodTypeDef,
  UniswapPositionsSolidityResponse
> = z.object({
  nonce: z.number().int(),
  operator: z.string(),
  token0: z.string(),
  token1: z.string(),
  fee: z.number().int(),
  tickLower: z.number().int(),
  tickUpper: z.number().int(),
  liquidity: z.number().int(),
  feeGrowthInside0LastX128: z.number().int(),
  feeGrowthInside1LastX128: z.number().int(),
  tokensOwed0: z.number().int(),
  tokensOwed1: z.number().int(),
  lpTokenAddress: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    tickLower: "tick_lower",
    tickUpper: "tick_upper",
    feeGrowthInside0LastX128: "fee_growth_inside0_last_x128",
    feeGrowthInside1LastX128: "fee_growth_inside1_last_x128",
    tokensOwed0: "tokens_owed0",
    tokensOwed1: "tokens_owed1",
    lpTokenAddress: "lp_token_address",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UniswapPositionsSolidityResponse$ {
  /** @deprecated use `UniswapPositionsSolidityResponse$inboundSchema` instead. */
  export const inboundSchema = UniswapPositionsSolidityResponse$inboundSchema;
  /** @deprecated use `UniswapPositionsSolidityResponse$outboundSchema` instead. */
  export const outboundSchema = UniswapPositionsSolidityResponse$outboundSchema;
  /** @deprecated use `UniswapPositionsSolidityResponse$Outbound` instead. */
  export type Outbound = UniswapPositionsSolidityResponse$Outbound;
}

export function uniswapPositionsSolidityResponseToJSON(
  uniswapPositionsSolidityResponse: UniswapPositionsSolidityResponse,
): string {
  return JSON.stringify(
    UniswapPositionsSolidityResponse$outboundSchema.parse(
      uniswapPositionsSolidityResponse,
    ),
  );
}

export function uniswapPositionsSolidityResponseFromJSON(
  jsonString: string,
): SafeParseResult<UniswapPositionsSolidityResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UniswapPositionsSolidityResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UniswapPositionsSolidityResponse' from JSON`,
  );
}
