/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UnsignedTransaction = {
  /**
   * The chain id of the transaction
   */
  chainId: string;
  /**
   * The data of the transaction
   */
  data: string;
  /**
   * The sender of the transaction
   */
  from: string;
  /**
   * The gas of the transaction
   */
  gas: string | null;
  /**
   * The recipient of the transaction
   */
  to: string;
  /**
   * The value of the transaction
   */
  value: string;
  /**
   * The nonce of the address
   */
  nonce: string;
  /**
   * The max fee per gas of the transaction
   */
  maxFeePerGas: string;
  /**
   * The max priority fee per gas of the transaction
   */
  maxPriorityFeePerGas: string;
};

/** @internal */
export const UnsignedTransaction$inboundSchema: z.ZodType<
  UnsignedTransaction,
  z.ZodTypeDef,
  unknown
> = z.object({
  chainId: z.string(),
  data: z.string(),
  from: z.string(),
  gas: z.nullable(z.string()),
  to: z.string(),
  value: z.string(),
  nonce: z.string(),
  maxFeePerGas: z.string(),
  maxPriorityFeePerGas: z.string(),
});

/** @internal */
export type UnsignedTransaction$Outbound = {
  chainId: string;
  data: string;
  from: string;
  gas: string | null;
  to: string;
  value: string;
  nonce: string;
  maxFeePerGas: string;
  maxPriorityFeePerGas: string;
};

/** @internal */
export const UnsignedTransaction$outboundSchema: z.ZodType<
  UnsignedTransaction$Outbound,
  z.ZodTypeDef,
  UnsignedTransaction
> = z.object({
  chainId: z.string(),
  data: z.string(),
  from: z.string(),
  gas: z.nullable(z.string()),
  to: z.string(),
  value: z.string(),
  nonce: z.string(),
  maxFeePerGas: z.string(),
  maxPriorityFeePerGas: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnsignedTransaction$ {
  /** @deprecated use `UnsignedTransaction$inboundSchema` instead. */
  export const inboundSchema = UnsignedTransaction$inboundSchema;
  /** @deprecated use `UnsignedTransaction$outboundSchema` instead. */
  export const outboundSchema = UnsignedTransaction$outboundSchema;
  /** @deprecated use `UnsignedTransaction$Outbound` instead. */
  export type Outbound = UnsignedTransaction$Outbound;
}

export function unsignedTransactionToJSON(
  unsignedTransaction: UnsignedTransaction,
): string {
  return JSON.stringify(
    UnsignedTransaction$outboundSchema.parse(unsignedTransaction),
  );
}

export function unsignedTransactionFromJSON(
  jsonString: string,
): SafeParseResult<UnsignedTransaction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnsignedTransaction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnsignedTransaction' from JSON`,
  );
}
