/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const VaultWithdrawRequestChain = {
  Arbitrum: "arbitrum",
  Base: "base",
  Ethereum: "ethereum",
} as const;
export type VaultWithdrawRequestChain = ClosedEnum<
  typeof VaultWithdrawRequestChain
>;

export type VaultWithdrawRequest = {
  actionType?: "VAULT_WITHDRAW" | undefined;
  /**
   * The vault address you are withdrawing from.
   */
  vaultAddress: string;
  /**
   * The amount of tokens to withdraw from the vault. If set to 'ALL', your total deposited token amount will be withdrawn.
   */
  amount?: any | undefined;
  /**
   * The address which will receive the tokens withdrawn. Defaults to the sender.
   */
  receiver?: string | null | undefined;
  chain: VaultWithdrawRequestChain;
  /**
   * The address of the transaction sender.
   */
  sender: string;
  /**
   * Determines whether to estimate gas costs for transactions, also verifying that the transaction can be successfully executed.
   */
  estimateGas?: boolean | undefined;
};

/** @internal */
export const VaultWithdrawRequestChain$inboundSchema: z.ZodNativeEnum<
  typeof VaultWithdrawRequestChain
> = z.nativeEnum(VaultWithdrawRequestChain);

/** @internal */
export const VaultWithdrawRequestChain$outboundSchema: z.ZodNativeEnum<
  typeof VaultWithdrawRequestChain
> = VaultWithdrawRequestChain$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VaultWithdrawRequestChain$ {
  /** @deprecated use `VaultWithdrawRequestChain$inboundSchema` instead. */
  export const inboundSchema = VaultWithdrawRequestChain$inboundSchema;
  /** @deprecated use `VaultWithdrawRequestChain$outboundSchema` instead. */
  export const outboundSchema = VaultWithdrawRequestChain$outboundSchema;
}

/** @internal */
export const VaultWithdrawRequest$inboundSchema: z.ZodType<
  VaultWithdrawRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  action_type: z.literal("VAULT_WITHDRAW").default("VAULT_WITHDRAW"),
  vault_address: z.string(),
  amount: z.any().optional(),
  receiver: z.nullable(z.string()).optional(),
  chain: VaultWithdrawRequestChain$inboundSchema,
  sender: z.string(),
  estimate_gas: z.boolean().default(true),
}).transform((v) => {
  return remap$(v, {
    "action_type": "actionType",
    "vault_address": "vaultAddress",
    "estimate_gas": "estimateGas",
  });
});

/** @internal */
export type VaultWithdrawRequest$Outbound = {
  action_type: "VAULT_WITHDRAW";
  vault_address: string;
  amount?: any | undefined;
  receiver?: string | null | undefined;
  chain: string;
  sender: string;
  estimate_gas: boolean;
};

/** @internal */
export const VaultWithdrawRequest$outboundSchema: z.ZodType<
  VaultWithdrawRequest$Outbound,
  z.ZodTypeDef,
  VaultWithdrawRequest
> = z.object({
  actionType: z.literal("VAULT_WITHDRAW").default("VAULT_WITHDRAW" as const),
  vaultAddress: z.string(),
  amount: z.any().optional(),
  receiver: z.nullable(z.string()).optional(),
  chain: VaultWithdrawRequestChain$outboundSchema,
  sender: z.string(),
  estimateGas: z.boolean().default(true),
}).transform((v) => {
  return remap$(v, {
    actionType: "action_type",
    vaultAddress: "vault_address",
    estimateGas: "estimate_gas",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VaultWithdrawRequest$ {
  /** @deprecated use `VaultWithdrawRequest$inboundSchema` instead. */
  export const inboundSchema = VaultWithdrawRequest$inboundSchema;
  /** @deprecated use `VaultWithdrawRequest$outboundSchema` instead. */
  export const outboundSchema = VaultWithdrawRequest$outboundSchema;
  /** @deprecated use `VaultWithdrawRequest$Outbound` instead. */
  export type Outbound = VaultWithdrawRequest$Outbound;
}

export function vaultWithdrawRequestToJSON(
  vaultWithdrawRequest: VaultWithdrawRequest,
): string {
  return JSON.stringify(
    VaultWithdrawRequest$outboundSchema.parse(vaultWithdrawRequest),
  );
}

export function vaultWithdrawRequestFromJSON(
  jsonString: string,
): SafeParseResult<VaultWithdrawRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VaultWithdrawRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VaultWithdrawRequest' from JSON`,
  );
}
